---
- name: Installing required modules for firewalld. python-firewall cocpit
  yum: name=python-firewall state=latest
  yum: name=cockpit state=latest

- name: Starting firewalld
  service: name=firewalld state=started

- name: Adding SSH to firewall
  firewalld: service=ssh permanent=true state=enabled
  notify:
    - restart firewalld

- name: adding HTTP to firewall
  firewalld: service=http permanent=true state=enabled
  notify:
    - restart firewalld

- name: adding HTTPS to firewall
  firewalld: service=https permanent=true state=enabled
  notify:
    - restart firewalld

- name: Setting firewalld to start on boot
  service: name=firewalld enabled=yes

