---
- name: Set TimeZone to Europe/Helsinki
  shell: timedatectl set-timezone Europe/Helsinki

- name: Install ntp
  yum: name=ntp state=latest

- name: Start ntpd and set it enabled
  service: name=ntpd enabled=yes
