---
- name: Disable root ssh login by using template
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0644

- name: Install cockpit
  yum: name={{ item }} state=latest
  with_items:
    - cockpit

- name: Update firewalld
  yum: name=firewalld state=latest

- name: Starting firewalld
  service: name=firewalld state=started

- name: Adding SSH to firewall
  firewalld: service=ssh permanent=true state=enabled
  notify:
    - restart firewalld

- name: adding HTTP to firewall
  firewalld: service=http permanent=true state=enabled
  notify:
    - restart firewalld

- name: adding HTTPS to firewall
  firewalld: service=https permanent=true state=enabled
  notify:
    - restart firewalld

- name: Setting firewalld to start on boot
  service: name=firewalld enabled=yes


